.PHONY: build run-scheduler run-worker run-api run-migrator

build:
	go build ./...

run-scheduler:
	go run ./cmd/scheduler

run-worker:
	go run ./cmd/worker

run-api:
	go run ./cmd/api

run-migrator:
	go run ./cmd/migrator